#!/bin/bash

$SPARK_HOME/bin/spark-submit \
--num-executors 22 \
--executor-cores 2 \
--executor-memory 8g \
--conf spark.driver.cores=4 \
--driver-memory 28g \
--conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
--jars ./jars/cats-core_2.11-1.0.0-RC2.jar,./jars/cats-free_2.11-1.0.0-RC2.jar,./jars/cats-effect_2.11-0.6.jar,./jars/cats-kernel_2.11-1.0.0-RC2.jar,./jars/config-1.3.1.jar,./jars/spark-root_2.11-0.1.14.jar,./jars/root4j-0.1.6.jar,./jars/bcel-5.2.jar \
--class "pgawrys.totem.Main" ./jars/spark-totem_2.11-1.0.jar $1 $2